# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

env:
  sqlUnitStore_ConnectionString: $(sqlUnitStore)
  pswd: $(dockerPassword) # Define dockerPassword in the Variables tab of this pipeline in Pipelines page of web interfac

variables:
  dockerId: HappyStorage  # Replace with your Docker ID for Docker Hub or the admin user name for the Azure Container Registry
  imageName: happystorage-blazor  # Replace with the name of the image you want to publish

steps:
- script: |
    docker build -t $(dockerId).azurecr.io/$(imageName) .
    docker login -u $(dockerId) -p $(pswd) $(dockerId).azurecr.io
    docker tag $(imageName) happystorage.azurecr.io/$(imageName)
    docker push $(dockerId).azurecr.io/$(imageName)