# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreInstaller@0
  displayName: 'Installing .NET Core SDK...'
  inputs:
    version: 3.0.100-preview7-012821

- task: DotNetCoreCLI@2
  displayName: 'Building App...'
  inputs:
    command: build
    projects: '**/*.csproj'
    configuration: $(BuildConfiguration)
- task: PublishBuildArtifacts@1
  displayName: 'Publishing Build Artifacts...'